language: node_js
node_js:
  - '7'
  - '8'
  - '9'
  - '10'
script:
  - npm test
after_script:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
